---
- name: Run prechecks
  include_tasks: prechecks.yml

- name: Ensure Keycloak database and Keycloak database user
  include_tasks: database.yml
  when: 
   - keycloak_db_ensure_database
   - inventory_hostname == play_hosts[0]
    
- name: Ensure Keycloak host config directory
  file:
    state: directory
    path: "{{ keycloak_host_config_dir }}"
    owner: root
    mode: 0644
  become: true

- name: Template Keycloak cache ISPN configuration
  template:
    src: "{{ keycloak_cache_config_file_template }}"
    dest: "{{ keycloak_host_config_dir }}/{{ keycloak_cache_config_file }}"
    owner: root
    mode: 0644
  become: true
  register: cache_ispn_configuration_file

- name: Ensure keycloak container is running
  docker_container:
    name: "{{ keycloak_docker_name }}"
    image: "{{ keycloak_docker_image }}:{{ keycloak_docker_tag }}"
    network_mode: host
    etc_hosts: "{{ keycloak_container.etc_hosts | default(omit) }}"
    volumes: "{{ _keycloak_volumes }}"
    comparisons:
      '*': strict
    restart_policy: "always"
    restart: "{{ cache_ispn_configuration_file is changed }}"
    env: "{{ _keycloak_env_vars }}"
    command: "{{ keycloak_docker_command }}"
  become: true
